auth:
  registry.cn-beijing.aliyuncs.com:
    username: $USERNAME
    password: $PASSWORD
images:
  registry.k8s.io/ingress-nginx/controller:v1.6.3: registry.cn-beijing.aliyuncs.com/paas-k8s/ingress-nginx-controller
  registry.k8s.io/ingress-nginx/opentelemetry:v20230107-helm-chart-4.4.2-2-g96b3d2165: registry.cn-beijing.aliyuncs.com/paas-k8s/ingress-nginx-opentelemetry
  registry.k8s.io/ingress-nginx/kube-webhook-certgen:v20220916-gd32f8c343: registry.cn-beijing.aliyuncs.com/paas-k8s/kube-webhook-certgen
  registry.k8s.io/defaultbackend-amd64:1.5: registry.cn-beijing.aliyuncs.com/paas-k8s/defaultbackend-amd64
  goharbor/nginx-photon:v2.7.0: registry.cn-beijing.aliyuncs.com/paas-k8s/harbor-nginx-photon
  goharbor/harbor-portal:v2.7.0: registry.cn-beijing.aliyuncs.com/paas-k8s/harbor-portal
  goharbor/harbor-core:v2.7.0: registry.cn-beijing.aliyuncs.com/paas-k8s/harbor-core
  goharbor/harbor-jobservice:v2.7.0: registry.cn-beijing.aliyuncs.com/paas-k8s/harbor-jobservice
  goharbor/registry-photon:v2.7.0: registry.cn-beijing.aliyuncs.com/paas-k8s/harbor-registry-photon
  goharbor/harbor-registryctl:v2.7.0: registry.cn-beijing.aliyuncs.com/paas-k8s/harbor-registryctl
  goharbor/chartmuseum-photon:v2.7.0: registry.cn-beijing.aliyuncs.com/paas-k8s/harbor-chartmuseum-photon
  goharbor/trivy-adapter-photon:v2.7.0: registry.cn-beijing.aliyuncs.com/paas-k8s/harbor-trivy-adapter-photon
  goharbor/notary-server-photon:v2.7.0: registry.cn-beijing.aliyuncs.com/paas-k8s/harbor-notary-server-photon
  goharbor/notary-signer-photon:v2.7.0: registry.cn-beijing.aliyuncs.com/paas-k8s/harbor-notary-signer-photon
  goharbor/harbor-db:v2.7.0: registry.cn-beijing.aliyuncs.com/paas-k8s/harbor-db
  goharbor/redis-photon:v2.7.0: registry.cn-beijing.aliyuncs.com/paas-k8s/harbor-redis-photon
  goharbor/harbor-exporter:v2.7.0: registry.cn-beijing.aliyuncs.com/paas-k8s/harbor-exporter
  
