auth:
  registry.cn-beijing.aliyuncs.com:
    username: $USERNAME
    password: $PASSWORD
images:
#   quay.io/jetstack/cert-manager-controller:v1.9.1,v1.10.2,v1.11.0: registry.cn-beijing.aliyuncs.com/paas-k8s/cert-manager-controller
#   quay.io/jetstack/cert-manager-webhook:v1.9.1,v1.10.2,v1.11.0: registry.cn-beijing.aliyuncs.com/paas-k8s/cert-manager-webhook
#   quay.io/jetstack/cert-manager-cainjector:v1.9.1,v1.10.2,v1.11.0: registry.cn-beijing.aliyuncs.com/paas-k8s/cert-manager-cainjector
#   quay.io/jetstack/cert-manager-ctl:v1.9.1,v1.10.2,v1.11.0: registry.cn-beijing.aliyuncs.com/paas-k8s/cert-manager-ctl
#   k8s.gcr.io/sig-storage/local-volume-provisioner:v2.4.0,v2.5.0: registry.cn-beijing.aliyuncs.com/paas-k8s/local-volume-provisioner
#   k8s.gcr.io/sig-storage/nfs-subdir-external-provisioner:v4.0.2: registry.cn-beijing.aliyuncs.com/paas-k8s/nfs-subdir-external-provisioner
#   registry.k8s.io/ingress-nginx/controller:v1.6.4: registry.cn-beijing.aliyuncs.com/paas-k8s/ingress-nginx-controller
#   registry.k8s.io/ingress-nginx/opentelemetry:v20230107-helm-chart-4.4.2-2-g96b3d2165: registry.cn-beijing.aliyuncs.com/paas-k8s/ingress-nginx-opentelemetry
#   registry.k8s.io/ingress-nginx/kube-webhook-certgen:v20220916-gd32f8c343: registry.cn-beijing.aliyuncs.com/paas-k8s/kube-webhook-certgen
#   registry.k8s.io/defaultbackend-amd64:1.5: registry.cn-beijing.aliyuncs.com/paas-k8s/defaultbackend-amd64
#   goharbor/nginx-photon:v2.7.0: registry.cn-beijing.aliyuncs.com/paas-k8s/harbor-nginx-photon
#   goharbor/harbor-portal:v2.7.0: registry.cn-beijing.aliyuncs.com/paas-k8s/harbor-portal
#   goharbor/harbor-core:v2.7.0: registry.cn-beijing.aliyuncs.com/paas-k8s/harbor-core
#   goharbor/harbor-jobservice:v2.7.0: registry.cn-beijing.aliyuncs.com/paas-k8s/harbor-jobservice
#   goharbor/registry-photon:v2.7.0: registry.cn-beijing.aliyuncs.com/paas-k8s/harbor-registry-photon
#   goharbor/harbor-registryctl:v2.7.0: registry.cn-beijing.aliyuncs.com/paas-k8s/harbor-registryctl
#   goharbor/chartmuseum-photon:v2.7.0: registry.cn-beijing.aliyuncs.com/paas-k8s/harbor-chartmuseum-photon
#   goharbor/trivy-adapter-photon:v2.7.0: registry.cn-beijing.aliyuncs.com/paas-k8s/harbor-trivy-adapter-photon
#   goharbor/notary-server-photon:v2.7.0: registry.cn-beijing.aliyuncs.com/paas-k8s/harbor-notary-server-photon
#   goharbor/notary-signer-photon:v2.7.0: registry.cn-beijing.aliyuncs.com/paas-k8s/harbor-notary-signer-photon
#   goharbor/harbor-db:v2.7.0: registry.cn-beijing.aliyuncs.com/paas-k8s/harbor-db
#   goharbor/redis-photon:v2.7.0: registry.cn-beijing.aliyuncs.com/paas-k8s/harbor-redis-photon
#   goharbor/harbor-exporter:v2.7.0: registry.cn-beijing.aliyuncs.com/paas-k8s/harbor-exporter
#   eclipse-temurin:17.0.8.1_1-jre-alpine,17.0.8.1_1-jdk-alpine,17.0.8.1_1-jre-jammy,17.0.8.1_1-jdk-jammy,8u382-b05-jdk-alpine,8u382-b05-jre-alpine: registry.cn-beijing.aliyuncs.com/officialimage/eclipse-temurin
#   eclipse-temurin:21_35-jdk-alpine,21_35-jre-alpine,21_35-jdk-jammy,21_35-jre-jammy: registry.cn-beijing.aliyuncs.com/officialimage/eclipse-temurin
#   redis:7.2.1-alpine: registry.cn-beijing.aliyuncs.com/officialimage/redis
#   redislabs/redisinsight:1.14.0: registry.cn-beijing.aliyuncs.com/officialimage/redisinsight
#   oliver006/redis_exporter:v1.51.0: registry.cn-beijing.aliyuncs.com/officialimage/redis_exporter
#   mysql:8.0.35-debian: registry.cn-beijing.aliyuncs.com/officialimage/mysql
#   prom/mysqld-exporter:v0.15.0: registry.cn-beijing.aliyuncs.com/officialimage/mysqld-exporter
#   mongo:4.4.25: registry.cn-beijing.aliyuncs.com/officialimage/mongo
  mongo-express:1.0.0-20-alpine3.18: registry.cn-beijing.aliyuncs.com/officialimage/mongo-express
#   bitnami/mongodb-exporter:0.39.0: registry.cn-beijing.aliyuncs.com/officialimage/mongodb-exporter
#   zookeeper:3.8.3: registry.cn-beijing.aliyuncs.com/officialimage/zookeeper
#   docker.elastic.co/elasticsearch/elasticsearch:8.10.4: registry.cn-beijing.aliyuncs.com/officialimage/elasticsearch
#   docker.elastic.co/kibana/kibana:8.10.4: registry.cn-beijing.aliyuncs.com/officialimage/kibana
#   docker.elastic.co/logstash/logstash:8.10.4: registry.cn-beijing.aliyuncs.com/officialimage/logstash
#   docker.elastic.co/beats/metricbeat:8.10.4: registry.cn-beijing.aliyuncs.com/officialimage/metricbeat
#   bitnami/elasticsearch-exporter:1.6.0: registry.cn-beijing.aliyuncs.com/officialimage/elasticsearch-exporter
#   grafana/grafana:10.1.5,10.0.9: registry.cn-beijing.aliyuncs.com/officialimage/grafana
#   prom/prometheus:v2.47.2: registry.cn-beijing.aliyuncs.com/officialimage/prometheus
#   prom/pushgateway:v1.6.2: registry.cn-beijing.aliyuncs.com/officialimage/pushgateway
#   solr:9.4.0: registry.cn-beijing.aliyuncs.com/officialimage/solr
#   quay.io/minio/minio:RELEASE.2023-09-30T07-02-29Z: registry.cn-beijing.aliyuncs.com/officialimage/minio
#   quay.io/minio/mc:RELEASE.2023-09-29T16-41-22Z: registry.cn-beijing.aliyuncs.com/officialimage/minio-mc
