auth:
  registry.cn-beijing.aliyuncs.com:
    username: $USERNAME
    password: $PASSWORD
images:
  registry.k8s.io/ingress-nginx/controller: registry.cn-beijing.aliyuncs.com/paas-k8s/ingress-nginx-controller
  registry.k8s.io/ingress-nginx/opentelemetry: registry.cn-beijing.aliyuncs.com/paas-k8s/ingress-nginx-opentelemetry
  registry.k8s.io/ingress-nginx/kube-webhook-certgen: registry.cn-beijing.aliyuncs.com/paas-k8s/kube-webhook-certgen
  registry.k8s.io/defaultbackend-amd64: registry.cn-beijing.aliyuncs.com/paas-k8s/defaultbackend-amd64
