# This is a basic workflow to help you get started with Actions

name: image-sync-arm64
on:
  push:
    branches: [ main ]
    paths:
      - 'config_source-arm64.yaml'
#  pull_request:
#    branches: [ main ]
#   schedule:
#     - cron: '0 14 * * 1'

env:
  IMAGE_SYNCER_VERSION: v1.5.5
  USERNAME: ${{ secrets.ALIYUN_USERNAME }}
  PASSWORD: ${{ secrets.ALIYUN_PASSWORD }}

jobs:
  image-sync:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: install image-sync tool
      run: |
        wget https://github.com/AliyunContainerService/image-syncer/releases/download/${IMAGE_SYNCER_VERSION}/image-syncer-${IMAGE_SYNCER_VERSION}-linux-amd64.tar.gz
        tar -zxf image-syncer-${IMAGE_SYNCER_VERSION}-linux-amd64.tar.gz
        
    - name: add sercret to file
      run: envsubst < config_source-arm64.yaml > config-arm64.yaml

    - name: sync images
      run: ./image-syncer --proc=10 --config=config-arm64.yaml --arch=arm64 --os=linux --retries=3
